### ISSUE TITLE
Linux build doesn't work on Ubuntu 20.04 due due glibc version mismatch

### ISSUE THREAD

**Issue by Some-Birb7190** [lilopkins/testangel#16]
Running the most recent release (0.3.1), the executable `testangel` won't load and the following output is displayed: 
```
user@host: /temp/testangel/build$ ./testangel
./testangel: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./testangel)
./testangel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./testangel)
./testangel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./testangel)
./testangel: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./testangel)
```
glib is installed and have done different troubleshooting to find the file that is being depended with no success. 

I am running a 64 bit system, 8 core CPU with 16GB of RAM. 

Any chance of some further troubleshooting I could try?
Thanks

**Comment by lilopkins** [comment]
release 0.6.0 may fix this problem for the executor, but unfortunately the GUI is not yet fixed.
