### ISSUE TITLE
Return type not cascading after save

### ISSUE THREAD

**Issue by Some-Birb7190** [lilopkins/testangel#216]
When saving an action, it does not trigger the type checking on flows
[Screencast from 05-12-24 22:36:38.webm](https://github.com/user-attachments/assets/a9dd7665-a2aa-4451-914b-2bea3996f389)

**Comment by Some-Birb7190** [comment]
This cascading type checking fails if the output is not a valid type, for example if you type 'Integre' instead of 'integer'

**Comment by lilopkins** [comment]
Good spot, it looks like it only tests type changes, not number of return changes or anything.

**Comment by lilopkins** [comment]
closed by #229
