### ISSUE TITLE
Add a demo action so users can get started when they open and aren't presented with an empty '+' list

### ISSUE THREAD

**Issue by lilopkins** [lilopkins/testangel#218]
As a user
I want to have a demo action included
So that it makes more sense how actions fit into the TestAngel workflow on first use.

**Comment by lilopkins** [comment]
This is probably best served by writing it when (if) the actions directory is first created.

**Comment by Some-Birb7190** [comment]
Maybe an action that just takes an input from the user and exports it as evidence?

**Comment by lilopkins** [comment]
closed by #229
